In [17]:
import torch
import torch.nn as nn

#version1

In [18]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [19]:
# Create dataset

features = torch.rand(10,5)
#create model

model = Model(features.shape[1])
model(features)

tensor([[0.5635],
        [0.5821],
        [0.5609],
        [0.5907],
        [0.5771],
        [0.5171],
        [0.5720],
        [0.5744],
        [0.5297],
        [0.5609]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear.weight

Parameter containing:
tensor([[ 0.0661,  0.3563,  0.3805, -0.3357, -0.1694]], requires_grad=True)

# Version2

In [21]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    #layer 1

    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()

    #layer 2
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    z1 = self.linear1(features)
    out = self.relu(z1)

    z2 = self.linear2(out)
    out = self.sigmoid(z2)

    return out

In [22]:
# Create dataset

features = torch.rand(10,5)
#create model

model = Model(features.shape[1])
model(features)

tensor([[0.4373],
        [0.4618],
        [0.4508],
        [0.4718],
        [0.4345],
        [0.4325],
        [0.4392],
        [0.4227],
        [0.4585],
        [0.4078]], grad_fn=<SigmoidBackward0>)

# version3

In [25]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network=nn.Sequential(
        nn.Linear(num_features,3), #index0
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
        )

  def forward(self,features):

    out=self.network(features)

    return out

In [26]:
# Create dataset

features = torch.rand(10,5)
#create model

model = Model(features.shape[1])
model(features)

tensor([[0.4337],
        [0.3943],
        [0.4028],
        [0.3985],
        [0.3918],
        [0.4120],
        [0.3997],
        [0.4381],
        [0.4247],
        [0.4086]], grad_fn=<SigmoidBackward0>)

In [30]:
model.network[0].weight

Parameter containing:
tensor([[ 0.2465,  0.1477, -0.0768,  0.3058, -0.0121],
        [ 0.4289,  0.0852,  0.3478, -0.4009, -0.4443],
        [ 0.2455, -0.2315,  0.2908,  0.1993,  0.0034]], requires_grad=True)

In [31]:
print("Layer 1 weights:")
print(model.network[0].weight)

print("\nLayer 1 bias:")
print(model.network[0].bias)

print("\nLayer 2 weights:")
print(model.network[2].weight)

print("\nLayer 2 bias:")
print(model.network[2].bias)

Layer 1 weights:
Parameter containing:
tensor([[ 0.2465,  0.1477, -0.0768,  0.3058, -0.0121],
        [ 0.4289,  0.0852,  0.3478, -0.4009, -0.4443],
        [ 0.2455, -0.2315,  0.2908,  0.1993,  0.0034]], requires_grad=True)

Layer 1 bias:
Parameter containing:
tensor([-0.3214, -0.1151,  0.1227], requires_grad=True)

Layer 2 weights:
Parameter containing:
tensor([[ 0.4179, -0.1170,  0.5399]], requires_grad=True)

Layer 2 bias:
Parameter containing:
tensor([-0.5626], requires_grad=True)


In [32]:
# visualize

!pip install torchinfo

In [33]:
from torchinfo import summary

summary( model,input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00