In [44]:
import numpy as np

data = np.array([
    [8.0,  1.0,  95.5],
    [9.0,  1.0,  92.0],
    [7.0,  2.0,  90.5],
    [7.5,  1.5,  88.0],
    [6.5,  2.0,  86.5],
    [6.0,  2.5,  85.0],
    [5.0,  3.0,  80.0],
    [4.0,  4.0,  70.5],
    [3.0,  5.0,  32.0],
    [2.0,  6.0,  25.5]
])

data

array([[ 8. ,  1. , 95.5],
       [ 9. ,  1. , 92. ],
       [ 7. ,  2. , 90.5],
       [ 7.5,  1.5, 88. ],
       [ 6.5,  2. , 86.5],
       [ 6. ,  2.5, 85. ],
       [ 5. ,  3. , 80. ],
       [ 4. ,  4. , 70.5],
       [ 3. ,  5. , 32. ],
       [ 2. ,  6. , 25.5]])

In [45]:
random_index=np.random.choice(10,size=10,replace=False)
print(random_index)

data=data[random_index]

# data

print(data)

[2 1 3 9 7 6 4 5 8 0]
[[ 7.   2.  90.5]
 [ 9.   1.  92. ]
 [ 7.5  1.5 88. ]
 [ 2.   6.  25.5]
 [ 4.   4.  70.5]
 [ 5.   3.  80. ]
 [ 6.5  2.  86.5]
 [ 6.   2.5 85. ]
 [ 3.   5.  32. ]
 [ 8.   1.  95.5]]


In [46]:
# feature and target extration

In [47]:
x=data[:,:2]
y=data[:,2:]

print(x)
print(y)

[[7.  2. ]
 [9.  1. ]
 [7.5 1.5]
 [2.  6. ]
 [4.  4. ]
 [5.  3. ]
 [6.5 2. ]
 [6.  2.5]
 [3.  5. ]
 [8.  1. ]]
[[90.5]
 [92. ]
 [88. ]
 [25.5]
 [70.5]
 [80. ]
 [86.5]
 [85. ]
 [32. ]
 [95.5]]


In [48]:
# train,test,split

train_index= int(len(data)*0.8)

x_train=x[:train_index,:]
y_train=y[:train_index,:]

x_test=x[train_index:,:]
y_test=y[train_index:,:]

x_test

array([[3., 5.],
       [8., 1.]])

In [49]:
#doing this split more easily

from sklearn.model_selection import train_test_split

x=data[:,:2]
y=data[:,2:]

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2)


X_test

array([[7., 2.],
       [4., 4.]])