In [ ]:
import numpy as np

arr=np.random.randint(1,100,size=(10,5))  #sample 10 , feature 5

In [ ]:
print(arr)
print(arr.shape)

[[99 66 52 19 77]
 [62 22 96 14  9]
 [35 82 68  3  1]
 [90 66 87 52 59]
 [57 62  1 19 25]
 [27  5 77 27 93]
 [93 77 60 93 30]
 [42  9 21 48 79]
 [ 2 76 10  5 39]
 [85 77 96 42 27]]
(10, 5)


In [ ]:
b=arr.reshape(5,10)
print(b)
print(b.shape)
print(b.ndim)

[[99 66 52 19 77 62 22 96 14  9]
 [35 82 68  3  1 90 66 87 52 59]
 [57 62  1 19 25 27  5 77 27 93]
 [93 77 60 93 30 42  9 21 48 79]
 [ 2 76 10  5 39 85 77 96 42 27]]
(5, 10)
2


In [ ]:
# flatten=b.flatten()
# print(flatten.ndim)
# print(flatten)


col_wise_flattening=b.flatten(order="F")
print(col_wise_flattening.ndim)
print(col_wise_flattening)


1
[99 35 57 93  2 66 82 62 77 76 52 68  1 60 10 19  3 19 93  5 77  1 25 30
 39 62 90 27 42 85 22 66  5  9 77 96 87 77 21 96 14 52 27 48 42  9 59 93
 79 27]


In [ ]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))

print(a)
print(b)

[[4 8 2]
 [1 3 1]]
[[26 21 29]
 [29 23 29]]


In [ ]:
#concatenate

concat_row=np.concatenate((a,b))
print(concat_row)

concat_col=np.concatenate((a,b),axis=1)
print(concat_col)

[[ 4  8  2]
 [ 1  3  1]
 [26 21 29]
 [29 23 29]]
[[ 4  8  2 26 21 29]
 [ 1  3  1 29 23 29]]


In [ ]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
#transpose

mat=np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

tran=mat.transpose() # or mat.T
print(tran)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#array split

a=np.random.randint(1,10,size=10)
print(a)



splitted_arr=np.split(a,2) #equal split
print(splitted_arr)

splitted_arr=np.array_split(a,3) #split
print(splitted_arr)


indexsplit=np.split(a,[2,5,7]) #split at those indexes
print(indexsplit)



[3 3 7 3 3 5 1 9 2 5]
[array([3, 3, 7, 3, 3]), array([5, 1, 9, 2, 5])]
[array([3, 3, 7, 3]), array([3, 5, 1]), array([9, 2, 5])]
[array([3, 3]), array([7, 3, 3]), array([5, 1]), array([9, 2, 5])]


## arithmetic operator and mathematical functions

In [ ]:
import numpy as np
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [ ]:
# mathematical function

# trigonometry

# sin , cos , tan takes values in radian

sin_val=np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

rad=np.deg2rad(deg_con)
print(rad)

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]
[ 10.   8.  30. 100.]


In [ ]:
#log
x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)

two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [ ]:
# different
print(x)
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumsum(x)
print(cumul)

[ 10   8  16 100]
134
[ 10  18  34 134]


In [ ]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

print(x>y)
print(x==y)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(x>y))
print(np.any(x==y))

[ True  True False  True]
[False False  True False]
False
True


# Sorting

In [ ]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z=x.copy()
print(z)
z.sort()
print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [ ]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [25]:
# 2d array sorting
mat = np.array([[10,3,5],
                [8,4,9]])

#axis auto 1
hor_sort = np.sort(mat)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# Searching

In [3]:
# np.where( condition , x , y ) if true x , otherwise replace with y

import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
index = np.where(x==8) # returns index
print(index)

arr=np.where(x>5,x,0)
print(arr)

(array([7]),)
[0 0 0 0 0 6 7 8 9]


In [5]:
mat = np.array([[10,3,5],
                [8,4,9]])
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [8]:
index=np.where(mat>5)
print(index)

arr = np.where(mat>5,0,mat) # returns array
print(arr)

(array([0, 1, 1]), array([0, 0, 2]))
[[0 3 5]
 [0 4 0]]


In [13]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maxval=np.max(x)
print(maxval)
minval=np.min(x)
print(minval)

maxval_index=np.argmax(x)
print(maxval_index)
minval_index=np.argmin(x)
print(minval_index)

100
8
1
2


# Count in ndarray

In [15]:
x = np.random.randint(1 ,100 , size =(100,))
print(x)

[66 57 75 37 31 45 75 96 23 50 27 23 77 20 63 74 85 29 41  9 13 79 80 43
 26 38 84 24 44 17 32 87 19 29 39 53 83 42 14 78 72 31  4 60 78 41 87 13
 70 91 27 56 97 83 64 87 20 67 91 84 44 86 79 36 61 81 47 47 76 44 36 20
 46 63 43 55  2 47 13 87 97  3 96 66 24 54  4 51 93 48 73 64 68 98  2 79
  3  7 55 41]


In [19]:
count=np.count_nonzero(x==13)

print(count)

3


In [20]:
uniqval=np.unique(x)

print(uniqval)

[ 2  3  4  7  9 13 14 17 19 20 23 24 26 27 29 31 32 36 37 38 39 41 42 43
 44 45 46 47 48 50 51 53 54 55 56 57 60 61 63 64 66 67 68 70 72 73 74 75
 76 77 78 79 80 81 83 84 85 86 87 91 93 96 97 98]


In [21]:
uniqval,freq=np.unique(x,return_counts=True)

print(uniqval)
print(freq)

[ 2  3  4  7  9 13 14 17 19 20 23 24 26 27 29 31 32 36 37 38 39 41 42 43
 44 45 46 47 48 50 51 53 54 55 56 57 60 61 63 64 66 67 68 70 72 73 74 75
 76 77 78 79 80 81 83 84 85 86 87 91 93 96 97 98]
[2 2 2 1 1 3 1 1 1 3 2 2 1 2 2 2 1 2 1 1 1 3 1 2 3 1 1 3 1 1 1 1 1 2 1 1 1
 1 2 2 2 1 1 1 1 1 1 2 1 1 2 3 1 1 2 2 1 1 4 2 1 2 2 1]


In [33]:
#data load

data = np.genfromtxt('student_scores.csv',delimiter=',',skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [44]:
#statistics

math_marks=data[::,:1]

print(math_marks.T)

max_mathMarks=np.max(math_marks)
print(max_mathMarks)
min_mathMarks=np.min(math_marks)
print(min_mathMarks)

avg=np.average(math_marks)
print(avg)

mean=np.mean(math_marks)
print(mean)

median=np.median(math_marks)
print(median)


#standard deviation
sd=np.std(math_marks)
print(sd)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.15
73.5
13.788672887555204


In [45]:
#corelation
import numpy as np

study = np.array([2, 4, 6, 8])
marks = np.array([50, 60, 75, 90])

corr = np.corrcoef(study, marks)
print(corr)

[[1.      0.99591]
 [0.99591 1.     ]]


# Linear Algebra

In [50]:
#mat multiplication
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

#way1

C=A@B
print(C)

#way2
print(np.dot(A,B))

#way3
print(np.matmul(A,B))

print(np.trace(B))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
17


In [53]:
#det

mat = np.array([[1, 2,4],
              [3, 4,3],
              [2,2,2]])


det=np.linalg.det(mat)
print(det)

rank=np.linalg.matrix_rank(mat)
print(rank)

-6.0
3


In [57]:
import numpy as np

mat = np.arange(16).reshape(4, 4)
print(mat)

center= mat[1:3,1:3]
print(center)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6]
 [ 9 10]]
