In [ ]:
import numpy as np

arr1=np.array([1,2,3])
print(type(arr1))
print(arr1)
print(arr1*5)

<class 'numpy.ndarray'>
[1 2 3]
[ 5 10 15]


# nd array

In [ ]:
import numpy as np
#1d arr
arr1=np.array([2,3,6,7,5])
#2d arr
arr2=np.array([[1,2,3],[4,5,6]])
#2d arr
arr3=np.array([[1,2,3],
              [4,5,6],
              [5,5,5]])
#3d arr

arr4=np.array([
                #1st floor
               [
                   [1,2,3],
                   [4,5,6]
               ],
              #2nd floor
               [
                   [4,4,5],
                   [9,0,4]
               ]
])


# array attributes

In [ ]:
#dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)

#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)
print(arr4.size)

1
2
2
3
(5,)
(2, 3)
(3, 3)
(2, 2, 3)
int64
int64
int64
int64
5
6
9
12


# nd array datatype

In [ ]:
arr=np.array([1,2,3])
print(arr.dtype)

arr=np.array([1.5,4,5])
print(arr.dtype)

int64
float64


In [ ]:
arr=np.array([1,2,4,3.1416]) # upcasted to flaot
print(arr.dtype)

arr=np.array([1,2,4,3.1416,"hellow"]) #upcasted to str
print(arr.dtype)
arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


# selecting datatype for an array

In [ ]:
arr=np.array([3,4,5],dtype=np.int16)
print(arr.dtype)

arr=np.array([3,4,5],dtype=np.int32)
print(arr.dtype)

arr=np.array([3,4,5],dtype=np.float16)
print(arr.dtype)


int16
int32
float16


# nd array creation from existing data

In [ ]:
#list

lst=[10,20,30,40.5]
arr=np.array(lst,dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U21


In [ ]:
#tuple

tup=(10,20,30,40.5)
arr=np.array(tup,dtype=np.int16)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40]
<class 'numpy.ndarray'>
int16
(4,)
1


In [ ]:
#set

st={10,20,30,40.5}
arr=np.array(st)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

{40.5, 10, 20, 30}
<class 'numpy.ndarray'>
object
()
0


In [ ]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [ ]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [ ]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [ ]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# Creating nd array from scratch

In [ ]:
arr=np.zeros([2,3],dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr=np.zeros_like(arr4)
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)


In [ ]:
arr=np.ones([4,3])

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr=np.ones_like(arr4)
print(arr)
print(arr.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [ ]:
arr=np.empty([2,3],dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr=np.empty_like(arr4)
print(arr)
print(arr.shape)


[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6
[[[4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]]

 [[4607182418800017408 4607182418800017408 4607182418800017408]
  [4607182418800017408 4607182418800017408 4607182418800017408]]]
(2, 2, 3)


In [ ]:
arr=np.full([3,2],11)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr=np.full([3,2],True)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[11 11]
 [11 11]
 [11 11]]
<class 'numpy.ndarray'>
int64
(3, 2)
2
6
[[ True  True]
 [ True  True]
 [ True  True]]
<class 'numpy.ndarray'>
bool
(3, 2)
2
6


In [ ]:
arr=np.full([3,2],np.inf)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr4,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[inf inf]
 [inf inf]
 [inf inf]]
<class 'numpy.ndarray'>
float64
(3, 2)
2
6
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(2, 2, 3)
float64


# array creation with random values

In [ ]:
# np.random.rand(shape)
import numpy as np

arr=np.random.rand(3,2) #0 to 1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[0.60520205 0.36590838]
 [0.07258837 0.82248392]
 [0.94953942 0.90771914]]
<class 'numpy.ndarray'>
float64
(3, 2)
2
6


In [ ]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[9 8 5]
 [9 6 1]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6


In [ ]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (2,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[66.5955207  88.46074845 93.92473473 82.2814449 ]
  [93.30701528 66.090027   96.83192819 84.58716034]
  [71.72015416 75.73222994 71.55665753 57.21619782]]

 [[86.92624444 54.28883439 71.20434611 68.2916674 ]
  [64.67064853 92.90079897 73.43845344 64.66361472]
  [79.23617998 92.68226841 86.15133916 60.44097709]]]
<class 'numpy.ndarray'>
float64
(2, 3, 4)
3
24


# array creation with range functions

In [ ]:
# np.arange(first , end , step ) -> similar to range function

arr=np.arange(1,13,2)

mat=arr.reshape(2,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1  3  5  7  9 11]
[[ 1  3  5]
 [ 7  9 11]]
<class 'numpy.ndarray'>
int64
(6,)
1
6


In [ ]:
# np.linspace(start , end(included) , koita)
# Creates numbers with equal spacing
# You specify how many values, not step

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [ ]:
# np.logspace(start , end(included) , koita )

# Creates numbers spaced logarithmically (exponential)
# Based on powers of 10 (default)

arr = np.logspace(0 , 4 ,6)
arr1 = np.logspace(0 , 4 ,6,base=2)

print(arr)
print(arr1)


[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra ( BONUS )


In [ ]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [ ]:
# identity matrix

identity_mat = np.eye(4)
print(identity_mat)
print(identity_mat.shape)


# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## indexing and slicing

In [ ]:
#slicing
#1d = arr[start:end:step]

arr1=[2,3,6,7,8,99,22]

arr1_mod = arr1[1:4].copy()
print(arr1_mod)
print(arr1)


arr1[1] = 2
arr1_mod[2] = 200
print(arr1_mod)
print(arr1)


[3, 6, 7]
[2, 3, 6, 7, 8, 99, 22]
[3, 6, 200]
[2, 2, 6, 7, 8, 99, 22]


In [ ]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

row0=arr[0:1,::]

col2=arr[::,2::]

slicemat=arr[1::,1::]

# print(arr[0,:])
print(row0)
print(col2)
print(slicemat)

[[10 20 30]]
[[30]
 [60]
 [90]]
[[50 60]
 [80 90]]


## Advanced/fancy Indexing

In [ ]:
lst = np.array([ 10 , 20 ,30 ,40 ])

values = lst[[0,3,3,1]]

print(values)

print(arr[[0,1],[1,2]])

print(arr[arr>20])

[10 40 40 20]
[20 60]
[30 40 50 60 70 80 90]


In [ ]:

print(arr)

#rowwise print
# for x in np.nditer(arr):
#   print(x)

  #col wise print

for x in np.nditer(arr,order="F"):
  print(x)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
40
70
20
50
80
30
60
90


# Extra practice problems

1. You have a list of temperatures recorded in Celsius. Your task is to:
Create a NumPy array from the given list.
Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
Print the new Fahrenheit array.


In [3]:
import numpy as np
celsius = [0, 10, 20, 30, 40]

c=np.array(celsius)
# print(c)

f=c*1.8+32
print(f"{c} values in Farenheit is {f}")

[ 0 10 20 30 40] values in Farenheit is [ 32.  50.  68.  86. 104.]


2.  You have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.
Print the array's shape, size, and data type.
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
Print the new array of lap times in minutes.


In [17]:
lapTimes=[120,2233,334,8080,23232,9292922,2323]

arr=np.array(lapTimes)
print(arr.shape)
print(arr.size)
print(arr.dtype)

arrInMin=arr/60

print(arrInMin)

(7,)
7
int64
[2.00000000e+00 3.72166667e+01 5.56666667e+00 1.34666667e+02
 3.87200000e+02 1.54882033e+05 3.87166667e+01]
