In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Device name:Tesla T4


# Create tensors

In [3]:
a=torch.empty(2,3)
a

tensor([[2.2599e-18, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.9348, 0.9842, 0.9709],
        [0.2149, 0.4635, 0.9187]])

In [8]:
torch.randint(10,(2,5))

tensor([[9, 7, 3, 8, 0],
        [4, 2, 5, 5, 8]])

In [9]:
torch.manual_seed(2)
torch.randint(10,(2,5))

tensor([[8, 7, 1, 4, 8],
        [9, 2, 5, 0, 1]])

In [10]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [11]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [13]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [14]:
x=torch.tensor([[1,2,3],[3,4,5]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.tensor([1.2,3.4,5.5],dtype=torch.int32)

tensor([1, 3, 5], dtype=torch.int32)

In [19]:
x=torch.tensor([[1,2,3],[3,4,5]])

In [20]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [21]:
x*2

tensor([[ 2,  4,  6],
        [ 6,  8, 10]])

In [22]:
x**2

tensor([[ 1,  4,  9],
        [ 9, 16, 25]])

In [23]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [1.5000, 2.0000, 2.5000]])

In [24]:
x//2

tensor([[0, 1, 1],
        [1, 2, 2]])

In [38]:
y=torch.randint(low=0,high=10,size=(2,3),dtype=torch.float32)
y

tensor([[9., 3., 5.],
        [6., 6., 1.]])

In [39]:
torch.sum(y,dim=0)

tensor([15.,  9.,  6.])

In [40]:
torch.sum(y,dim=1)

tensor([17., 13.])

In [41]:
torch.sum(y)

tensor(30.)

In [42]:
torch.mean(y,dtype=torch.float32)

tensor(5.)

In [43]:
torch.std(y)

tensor(2.7568)

In [44]:
torch.max(y)

tensor(9.)

In [45]:
torch.argmax(y)

tensor(0)

In [46]:
mata=torch.randint(size=(2,3),low=2,high=11,dtype=torch.float32)
matb=torch.randint(size=(3,2),low=2,high=11,dtype=torch.float32)

In [47]:
mata,matb

(tensor([[ 5., 10., 10.],
         [ 5.,  4., 10.]]),
 tensor([[ 5.,  6.],
         [ 3., 10.],
         [ 7.,  6.]]))

In [48]:
torch.matmul(mata,matb)

tensor([[125., 190.],
        [107., 130.]])

In [56]:
torch.transpose(mata,0,1)

tensor([[ 5.,  5.],
        [10.,  4.],
        [10., 10.]])

In [61]:
matc=torch.randint(size=(2,2),low=2,high=11,dtype=torch.float32)
matc

tensor([[4., 5.],
        [2., 2.]])

In [62]:
torch.inverse(matc)

tensor([[-1.0000,  2.5000],
        [ 1.0000, -2.0000]])

In [66]:
k=torch.tensor([2,3,4,5,1])
k

tensor([2, 3, 4, 5, 1])

In [67]:
torch.log(k)

tensor([0.6931, 1.0986, 1.3863, 1.6094, 0.0000])

In [68]:
torch.exp(k)

tensor([  7.3891,  20.0855,  54.5981, 148.4132,   2.7183])

In [69]:
torch.sigmoid(k)

tensor([0.8808, 0.9526, 0.9820, 0.9933, 0.7311])

In [79]:
torch.softmax(k.float(),dim=0)

tensor([0.0317, 0.0861, 0.2341, 0.6364, 0.0117])

In [80]:
torch.relu(k)

tensor([2, 3, 4, 5, 1])

In [81]:
a=torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [82]:
b=a.clone()
b

tensor([1, 2, 3, 4, 5])

In [83]:
id(a),id(b)

(132497488260992, 132497488999712)